version: "3.8"
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                - REACT_APP_NAME=commander-prod
        ports: 
            - "8080:80"            